import { IsString, IsNotEmpty, ValidateNested } from 'class-validator';

import { Type } from 'class-transformer';

class User {
  @IsString()
  @IsNotEmpty()
  id: string;

  @IsString()
  @IsNotEmpty()
  name: string;
}

export class PolybaseProject {
  id: string;
  name: string;
  url: string;
}

export class ProjectDto {
  /**
   * Title of the project
   * @example "Picasso Project"
   */
  @IsNotEmpty()
  @IsString()
  name: string;

  /**
   * URL of the project
   * @example "https://attribute.io"
   */
  @IsString()
  url: string;
}

export class CreateProject extends ProjectDto {
  // The user is not expected to insert the id of the project
  //   @IsNotEmpty()
  //   @IsString()
  //   id: string;
  // We will see how we will do owner, but for now we already get it from the token generated by the user
  //   @IsNotEmpty()
  //   @ValidateNested()
  //   @Type(() => User)
  //   owner: User;
}

export class UpdateProject extends ProjectDto {}
